<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>MQLite</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            .contents {
                text-align: left;
                max-width: 700px;
                margin: 0px auto;
            }
        </style>
    </head>
    <body>
        <h1>MQLite</h1>
        <div>message queue with SQLite</div>
        <div class="contents">
            <h2>APIs</h2>
            <ul>
                <li><code>/api/send/{type}?message=[message]&access_token=[access_token]</code></li>
                <li><code>/api/get/{type}?access_token=[access_token]</code></li>
            </ul>
        </div>
        
    </body>
</html>
